export const SET_ETH_AMOUNT = "SET_ETH_AMOUNT"
export const SET_USDT_AMOUNT = "SET_USDT_AMOUNT"
export const SET_TOKEN_AMOUNT = "SET_TOKEN_AMOUNT"
export const SET_TOKEN_AMOUNTUSD = "SET_TOKEN_AMOUNTUSD"